### ISSUE TITLE
Release: 2.1

### ISSUE THREAD

**Issue by pendo324** [pendo324/EssentialNowPlaying#42]
Meta-issue tracking the progress on the 2.1 release.

- [ ] Fix NativeMessagingInterface (#41)
- [ ] Add support for new Spotify web player url (#35)
- [ ] Add support for BandCamp (#6)
- [ ] Investigate Plex / Add Plex support (#34)

**Comment by pendo324** [comment]
I'll start working on this on the weekend, but pull requests are definitely welcome!
